apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: shweta1902/auth-service:latest  # Use the locally built image
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_URI
              value: "mongodb+srv://iib2022011:1234@blogcluster.n0x3qcl.mongodb.net/?retryWrites=true&w=majority&appName=BlogCluster"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          # Readiness and Liveness Probes
          readinessProbe:
            httpGet:
              path: /auth/health/readiness  # Use this if you want a specific readiness route
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /auth/health/liveness  # Use this if you want a specific liveness route
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: NodePort

