apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: shweta1902/post-service:latest
          ports:
            - containerPort: 5002
          env:
            - name: MONGO_URI
              value: "mongodb+srv://iib2022011:1234@blogcluster.n0x3qcl.mongodb.net/?retryWrites=true&w=majority&appName=BlogCluster"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /post/health/readiness
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /post/health/liveness
              port: 5002
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: post
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: NodePort

